spring:
  h2:
    console.enabled: true
    datasource:
      url: jdbc:h2:mem:testdb
      username: sa
      password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
taco:
  orders:
    pageSize: 10